services:
  frontend-webapp:
    image: moneyfy-app.azurecr.io/frontend.moneyfy.webapp:${ImageTag}
    container_name: moneyfy-frontend
    ports:
      - 7103:8031
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8031
      - AppSettings:BackendServicesUrl=http://gateway-webapi:8010
      - AppSettings:Authority=${WebAuthority}
      - AppSettings:ClientId=${WebClientId}
      - AppSettings:Scope=${WebScope}
      - Authentication:Schemes:OpenIdConnect:ClientSecret=${WebClientSecret}
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/

  gateway-webapi:
    image: moneyfy-app.azurecr.io/gateway.moneyfy.webapi:${ImageTag}
    container_name: moneyfy-gateway
    ports:
      - 5281:8010
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8010
      - GatewaySettings:Authority=${Authority}
      - GatewaySettings:Audience=${Audience}
      - GatewaySettings:MaxWindowSecondsTimeout=${MaxWindowSecondsTimeout}
      - GatewaySettings:MaxPermitCounters=${MaxPermitCounters}
      - GatewaySettings:SeqServerUrl=http://seq-server:5341
      - ReverseProxy:Routes:PaymentsRoute:Match:Path=${PaymentsRoute}
      - ReverseProxy:Routes:NotificationsRoute:Match:Path=${NotificationsRoute}
      - ReverseProxy:Routes:IncomesRoute:Match:Path=${IncomesRoute}
      - ReverseProxy:Routes:ExpensesRoute:Match:Path"${ExpensesRoute}
      - ReverseProxy:Clusters:PaymentsCluster:Destinations:Destination1:Address=http://payments-webapi:8029/payments
      - ReverseProxy:Clusters:NotificationsCluster:Destinations:Destination1:Address=http://notifications-webapi:8030/notifications
      - ReverseProxy:Clusters:IncomesCluster:Destinations:Destination1:Address=http://incomes-webapi:8028/incomes
      - ReverseProxy:Clusters:ExpensesCluster:Destinations:Destination1:Address=http://expenses-webapi:8027/expenses
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/

  expenses-webapi:
    image: moneyfy-app.azurecr.io/expenses.moneyfy.webapi:${ImageTag}
    container_name: moneyfy-expenses
    ports:
      - 5019:8027
    links:
      - mongo-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8027
      - WebApiSettings:Authority=${Authority}
      - WebApiSettings:Audience=${Audience}
      - WebApiSettings:KeyVaultName=${KeyVaultName}
      - WebApiSettings:DBConnection=mongodb://${DBUserName}:${DBUserPass}@mongo-db:27017
      - WebApiSettings:SeqServerUrl=http://seq-server:5341
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/

  incomes-webapi:
    image: moneyfy-app.azurecr.io/incomes.moneyfy.webapi:${ImageTag}
    container_name: moneyfy-incomes
    ports:
      - 5089:8028
    links:
      - mongo-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8028
      - WebApiSettings:Authority=${Authority}
      - WebApiSettings:Audience=${Audience}
      - WebApiSettings:KeyVaultName=${KeyVaultName}
      - WebApiSettings:DBConnection=mongodb://${DBUserName}:${DBUserPass}@mongo-db:27017
      - WebApiSettings:SeqServerUrl=http://seq-server:5341
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/

  payments-webapi:
    image: moneyfy-app.azurecr.io/payments.moneyfy.webapi:${ImageTag}
    container_name: moneyfy-payments
    ports:
      - 5063:8029
    links:
      - mongo-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8029
      - WebApiSettings:Authority=${Authority}
      - WebApiSettings:Audience=${Audience}
      - WebApiSettings:KeyVaultName=${KeyVaultName}
      - WebApiSettings:DBConnection=mongodb://${DBUserName}:${DBUserPass}@mongo-db:27017
      - WebApiSettings:SeqServerUrl=http://seq-server:5341
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/

  notifications-webapi:
    image: moneyfy-app.azurecr.io/notifications.moneyfy.webapi:${ImageTag}
    container_name: moneyfy-notifications
    ports:
      - 5244:8030
    links:
      - mongo-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8030
      - WebApiSettings:Authority=${Authority}
      - WebApiSettings:Audience=${Audience}
      - WebApiSettings:KeyVaultName=${KeyVaultName}
      - WebApiSettings:DBConnection=mongodb://${DBUserName}:${DBUserPass}@mongo-db:27017
      - WebApiSettings:SeqServerUrl=http://seq-server:5341
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/

  mongo-db:
    image: mongo
    container_name: moneyfy-db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DBUserName}
      - MONGO_INITDB_ROOT_PASSWORD=${DBUserPass}
    volumes:
      - mongodbdata:/data/db

  seq-server:
    image: datalust/seq
    container_name: moneyfy-seq
    environment:
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 80:80
    volumes:
      - seqdata:/data

volumes:
  mongodbdata:
  seqdata: