apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: expenses-webapi-mapping
spec:
  # here (hostname:) must be set the DNS associated with the emissary-ingress external ip address in the Azure Portal
  hostname: moneyfy-app.eastus.cloudapp.azure.com
  prefix: /expenses/
  service: expenses-webapi-service.expenses-webapi # the id after the . it corresponding to namespace or selector label of the service
  allow_upgrade: # to allow web socket connections from the frontend portal through the gateway to the microservice
    - websocket

---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: incomes-webapi-mapping
spec:
  hostname: moneyfy-app.eastus.cloudapp.azure.com
  prefix: /incomes/
  service: incomes-webapi-service.incomes-webapi
  allow_upgrade:
    - websocket

---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: payments-webapi-mapping
spec:
  hostname: moneyfy-app.eastus.cloudapp.azure.com
  prefix: /payments/
  service: payments-webapi-service.payments-webapi
  allow_upgrade:
    - websocket

---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: notifications-webapi-mapping
spec:
  hostname: moneyfy-app.eastus.cloudapp.azure.com
  prefix: /notifications/
  service: notifications-webapi-service.notifications-webapi
  allow_upgrade:
    - websocket

---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: seq-mapping
spec:
  hostname: moneyfy-app.eastus.cloudapp.azure.com
  prefix: /seq/
  service: seq.observability
